#+TITLE: ttybitnik/suckless
#+AUTHOR: Vinicius Moraes
#+EMAIL: vinicius.moraes@eternodevir.com
#+OPTIONS: num:nil

This repository contains the source code and configuration files for my suckless *dwm*, *dmenu*, *dwmblocks*, *st*, and *slock*. These are minimalist and lightweight tools designed for users who want a customizable and efficient system.

**** Table of contents                                             :TOC_4:
  - [[#features][Features]]
  - [[#dependencies][Dependencies]]
      - [[#main][Main]]
  - [[#instructions][Instructions]]
    - [[#prerequisites][Prerequisites]]
    - [[#installation][Installation]]
    - [[#usage][Usage]]
    - [[#configuration][Configuration]]
  - [[#license][License]]

** Features

List of features available in the source code and configuration files of this repository:

| *dwm*       | autostart, rotatestack, centeredwindowname, centeredmaster, centeredfloatingmaster, pertag, xrdb, vanity gaps, systray, dwmc, scratchpads |
| *dwmblocks* | statuscmd                                                                                                                                 |
| *dmenu*     | xresources                                                                                                                                |
| *st*        | xresources, xresources reload, alpha, scrollback, scrollback mouse, visualbell                                                           |
| *slock*     | dpms                                                                                                                                      |

** Dependencies

Dependencies needed for my build to work correctly: 

**** Main

+ My [[https://github.com/ttybitnik/dotfiles][dotfiles]]
+ Xsettingsd

** Instructions
*** Prerequisites

Before installing the suckless tools, make sure that you have the following prerequisites installed:

+ =make=
+ =gcc=
+ =libx11-dev=
+ =libxft-dev=
+ =libxinerama-dev=

*** Installation

1) Clone the repository:
   #+begin_src shell
     mkdir -p ~/.config/suckless/
     cd ~/.config/suckless
     git clone https://github.com/ttybitnik/suckless.git .
   #+end_src

2) Build and install dwm:
   #+begin_src shell
     cd dwm
     sudo make clean install
     cd ..
   #+end_src

3) Build and install dmenu:
   #+begin_src shell
     cd dmenu
     sudo make clean install
     cd ..
   #+end_src

4) Build and install dwmblocks:
   #+begin_src shell
     cd dwmblocks
     sudo make clean install
     cd ..
   #+end_src

5) Build and install st:
   #+begin_src shell
     cd st
     sudo make clean install
     cd ..
   #+end_src

6) Build and install slock:
   #+begin_src shell
     cd slock
     sudo make clean install
     cd ..
   #+end_src

*** Usage

To use dwm, dmenu, dwmblocks, st, and slock, simply launch them from your terminal or from my dotfiles’ startup script.

- To launch dwm, run =exec dwm= in your =.xinitrc= or =.xsession= file.
- To launch dmenu, press =ProprietaryKey p= to run the dwm =dmenu_run= command.
- Dwmblocks is automatically loaded through my dwm's startup script when you launch dwm.
- To launch st, press =ProprietaryKey y=.
- To launch slock, run =slock= in dmenu. 

*** Configuration

After installing dwm, dmenu, dwmblocks, st, and slock, you can customize their configuration by editing the corresponding =config.h= files. You can find these files in the =dwm/=, =dmenu/=, and =dwmblocks/= directories, respectively.

Here are some examples of configurations you can modify:

- Add or remove key bindings for dwm in the =config.def.h= file in the =dwm/= directory.
- Change the font and color scheme for dmenu in the =config.def.h= file in the =dmenu/= directory.
- Add or remove status modules for dwmblocks in the =blocks.def.h= file in the =dwmblocks/= directory.
- Customize the colors and fonts for st in the =config.def.h= file in the =st/= directory.
- Configure slock options, such as the the time delay, in the =config.def.h= file in the =slock/= directory.

** License

This project is licensed under the MIT License, *unless an exception is made explicit in context*.

See the =LICENSE= files for more information.
