#+TITLE: Suckless.w0lper	
#+AUTHOR: Vinicius Moraes
#+EMAIL: vinicius.moraes@eternodevir.com
#+OPTIONS: num:nil

This repository contains the source code and configuration files for my suckless *dwm*, *dmenu*, and *dwmblocks*. These are minimalist and lightweight tools designed for users who want a customizable and efficient system.

**** Table of contents                                             :TOC_4:
  - [[#features][Features]]
  - [[#dependencies][Dependencies]]
    - [[#main][Main]]
    - [[#suggestions][Suggestions]]
  - [[#instructions][Instructions]]
    - [[#prerequisites][Prerequisites]]
    - [[#installation][Installation]]
    - [[#usage][Usage]]
    - [[#configuration][Configuration]]
  - [[#miscellaneous][Miscellaneous]]
    - [[#ytfzf-and-yt-dlp][Ytfzf and yt-dlp]]
    - [[#mouse-speed-xorg][Mouse speed (Xorg)]]
  - [[#license][License]]

** Features

List of features available in the source code and configuration files of this repository:

+ Dwm
  + Autostart
  + Rotate stack
  + Systray
  + Vanity gaps
+ Dmenu
+ Dwmblocks

** Dependencies

Dependency needed for my build to work correctly, as well as some suggested tools and applications: 

**** Main

+ My [[https://github.com/w0lper/dotfiles][dotfiles]]

**** Suggestions

+ Qutebrowser
+ Nitrogen
+ Ytfzf
+ Yt-dlp
+ Mpv
+ Devour
+ Fzf
+ Xclip
+ Pulsemixer
+ Redshift

** Instructions
*** Prerequisites

Before installing dwm, dmenu, and dwmblocks, make sure that you have the following prerequisites installed:

+ =make=
+ =gcc=
+ =libx11-dev=
+ =libxft-dev=
+ =libxinerama-dev=

*** Installation

1) Clone the repository:
   #+begin_src shell
     mkdir -p ~/.config/suckless/
     cd ~/.config/suckless
     git clone https://github.com/w0lper/suckless.git .
   #+end_src

2) Build and install dwm:
   #+begin_src shell
     cd dwm
     sudo make clean install
     cd ..
   #+end_src

3) Build and install dmenu:
   #+begin_src shell
     cd dmenu
     sudo make clean install
     cd ..
   #+end_src

4) Build and install dwmblocks:
   #+begin_src shell
     cd dwmblocks
     sudo make clean install
     cd ..
   #+end_src

*** Usage

To use dwm, dmenu, and dwmblocks, simply launch them from your terminal or from my dotfiles’ startup script.

- To launch dwm, run =exec dwm= in your =.xinitrc= or =.xsession= file.
- To launch dmenu, press =ProprietaryKey p=  to run the dwm =dmenu_run= command.
- Dwmblocks is automatically loaded through my dwm's startup script when you launch dwm.

*** Configuration

After installing dwm, dmenu, and dwmblocks, you can customize their configuration by editing the corresponding =config.h= files. You can find these files in the =dwm/=, =dmenu/=, and =dwmblocks/= directories, respectively.

Here are some examples of configurations you can modify:

- Add or remove key bindings for dwm in the =config.def.h= file in the =dwm/= directory.
- Change the font and color scheme for dmenu in the =config.def.h= file in the =dmenu/= directory.
- Add or remove status modules for dwmblocks in the =blocks.def.h= file in the =dwmblocks/= directory.

** Miscellaneous

This section contains additional fine-tuning configurations for the packages and projects that I use in conjunction with my suckless tools.

**** Ytfzf and yt-dlp

To improve the performance of ytfzf, I recommend creating a symbolic link from =/usr/local/bin/yt-dlp= to =/usr/bin/youtube-dl=. This makes *ytfzf* work through *yt-dlp* instead of the hard-coded *youtube-dl*. Additionally, make sure to install =ffmpeg= for the highest video quality.


**** Mouse speed (Xorg)

To adjust the mouse speed in Xorg, create the file =/etc/X11/xorg.conf.d/50-mouse-acceleration.conf= with the following content:

#+BEGIN_SRC bash
Section "InputClass"
	Identifier "My Mouse"
	Driver "libinput"
	MatchIsPointer "yes"
	Option "AccelProfile" "flat"
	Option "AccelSpeed" "0"
EndSection
#+END_SRC

After saving the file, restart Xorg.

** License

This project is licensed under the MIT License, unless an exception is made explicit in context.

See the =LICENSE= files for more information.
